### ISSUE TITLE
Is trickster really necessary?

### ISSUE THREAD

**Issue by tenmozes** [swarmstack/victoria-metrics#1]
Hi, i'm one of VictoriaMetrics contributors

`If you need to scale your metrics application even beyond the performance capabilities of VictoriaMetrics, see Trickster for an in-memory cache that can front-end VictoriaMetrics or Prometheus for possible further performance gains.`

Does trickster improve read performance of VM? If you have any information please share

Why am i curious? VM has cache in an inside single node or in vmselect in cluster version which works similar to the trickster. E.g. you have a dashboard with query `rate(vm_rows_merged_total[5m]` which refreshes data every 5 minutes. Cache stores the result of a query and after 5m will request only missing data from storage with range [now-5m, now].

thanks

**Comment by mh720** [comment]
Thanks for the feedback. I’ll adjust documentation to remove reference to fronting VictoriaMetrics with Trickster; I wasn’t aware of the similar in-memory caching function for recently accessed metrics.

**Comment by tenmozes** [comment]
thank you, we will update VM documentation and add Cache section
